# Generated by Django 5.2.3 on 2025-06-22 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='Numéro de Demande')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant demandé')),
                ('loan_type', models.CharField(choices=[('personal', 'Prêt Personnel'), ('housing', 'Prêt Immobilier'), ('vehicle', 'Prêt Véhicule'), ('education', 'Prêt Étudiant'), ('other', 'Autre')], default='personal', max_length=50, verbose_name='Type de prêt')),
                ('repayment_period_months', models.IntegerField(verbose_name='Durée de remboursement (mois)')),
                ('purpose', models.TextField(blank=True, verbose_name='Objectif du prêt')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('disbursed', 'Décaissé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut de la demande')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('date_approved_rejected', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation/rejet")),
                ('admin_comments', models.TextField(blank=True, verbose_name="Commentaires de l'administrateur")),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant approuvé')),
                ('applicant', models.ForeignKey(limit_choices_to={'role': 'fonctionnaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'administrateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loan_applications', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé/Rejeté par')),
            ],
            options={
                'verbose_name': 'Demande de prêt',
                'verbose_name_plural': 'Demandes de prêt',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
