# Generated by Django 5.2.3 on 2025-07-13 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_remboursement', models.IntegerField(help_text='Durée en mois')),
                ('adresse_bien', models.TextField()),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En cours de traitement'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('archive', 'Archivé')], default='soumis', max_length=20)),
                ('numero_dossier', models.CharField(max_length=100, unique=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('fonctionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('type_pret', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.typepret')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En cours de traitement'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('archive', 'Archivé')], max_length=20)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='loans.demandepret')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pieces_jointes/')),
                ('nom', models.CharField(max_length=255)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='loans.demandepret')),
            ],
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
    ]
