# Generated by Django 5.2.3 on 2025-07-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_typepret_demandepret_historiquestatut_piecejointe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PieceJointe',
        ),
    ]
